// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAppTb01Lab1_LALC.Models;

namespace WebAppTb01Lab1_LALC.Migrations
{
    [DbContext(typeof(AutomovelContext))]
    partial class AutomovelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppTb01Lab1_LALC.Models.Automovel", b =>
                {
                    b.Property<int>("AutomovelId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<bool>("Disponivel");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Tipo")
                        .HasMaxLength(300);

                    b.HasKey("AutomovelId");

                    b.ToTable("Automovel");
                });
#pragma warning restore 612, 618
        }
    }
}
